export { AboutBlock } from "@/payload/blocks/AboutBlock";
// export { ArchiveBlock } from "@/payload/blocks/ArchiveBlock";
// export { BannerBlock } from "@/payload/blocks/BannerBlock";
// export { CallToActionBlock } from "@/payload/blocks/CallToActionBlock";
export { CardsBlock } from "@/payload/blocks/CardsBlock";
// export { CodeBlock } from "@/payload/blocks/CodeBlock";
export { ContactBlock } from "@/payload/blocks/ContactBlock";
// export { ContentBlock } from "@/payload/blocks/ContentBlock";
export { FaqBlock } from "@/payload/blocks/FaqBlock";
// export { FormBlock } from "@/payload/blocks/FormBlock";
export { HrBlock } from "@/payload/blocks/HrBlock";
export { MediaBlock } from "@/payload/blocks/MediaBlock";
export { TitleBlock } from "@/payload/blocks/TitleBlock";
